### ISSUE TITLE
Do not Consume a Command without a Response

### ISSUE THREAD

**Issue by jumpingpxl** [tmbRandy/GrieferGames-Addon-by-TMB#1]
In the class PayAllCommand, you consume the command even if the user is not on GrieferGames. If this is intended, please respond to the user. If not, return false.

https://github.com/tmbRandy/GrieferGames-Addon-by-TMB/blob/7da03523c85e1e355d7fc5fa0f8870fdf713e4a8/core/src/main/java/tmb/randy/tmbgriefergames/core/commands/PayAllCommand.java#L19

**Comment by tmbRandy** [comment]
Thank you. I fixed it for the next release.
